# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Use SECRET_KEY from GitHub Secrets
      env:
        SECRET_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo "Using secret key in environment: $SECRET_KEY"
        # Your commands that use the SECRET_KEY
        node your_script.js
